- name: Create keepalived.conf on control_panel nodes
  ansible.builtin.copy:
    dest: /etc/keepalived/keepalived.conf
    content: |
      global_defs {
          enable_script_security
          script_user nobody
      }

      vrrp_script check_apiserver {
        script "/etc/keepalived/check_apiserver.sh"
        interval 3
      }

      vrrp_instance VI_1 {
          state BACKUP
          interface ens33
          virtual_router_id 5
          priority 100
          advert_int 1
          nopreempt
          authentication {
              auth_type PASS
              auth_pass ZqSj#f1G
          }
          virtual_ipaddress {
              192.168.62.200
          }
          track_script {
              check_apiserver
          }
      }
    owner: root
    group: root
    mode: '0644'
  when: "'control_panel' in group_names"

- name: Create check_apiserver.sh on control_panel nodes
  ansible.builtin.copy:
    dest: /etc/keepalived/check_apiserver.sh
    content: |
      #!/bin/sh
      # File: /etc/keepalived/check_apiserver.sh

      APISERVER_VIP=192.168.62.200
      APISERVER_DEST_PORT=8888
      PROTO=http

      errorExit() {
          echo "*** $*" 1>&2
          exit 1
      }

      curl --silent --max-time 2 --insecure ${PROTO}://localhost:${APISERVER_DEST_PORT}/ -o /dev/null || errorExit "Error GET ${PROTO}://localhost:${APISERVER_DEST_PORT}/"
      if ip addr | grep -q ${APISERVER_VIP}; then
          curl --silent --max-time 2 --insecure ${PROTO}://${APISERVER_VIP}:${APISERVER_DEST_PORT}/ -o /dev/null || errorExit "Error GET ${PROTO}://${APISERVER_VIP}:${APISERVER_DEST_PORT}/"
      fi
    owner: root
    group: root
    mode: '0755'
  when: "'control_panel' in group_names"

- name: Ensure check_apiserver.sh is executable
  ansible.builtin.file:
    path: /etc/keepalived/check_apiserver.sh
    mode: '0755'
  when: "'control_panel' in group_names"

- name: Enable keepalived service
  ansible.builtin.systemd:
    name: keepalived
    enabled: yes
  when: "'control_panel' in group_names"

- name: Start keepalived service
  ansible.builtin.systemd:
    name: keepalived
    state: started
  when: "'control_panel' in group_names"
