- name: Ensure required kernel modules are listed in /etc/modules-load.d/k8s.conf
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: true
  loop:
    - overlay
    - br_netfilter

- name: Load required kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Apply sysctl params
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
    - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { key: "net.ipv4.ip_forward", value: "1" }

- name: Set swappiness to 0 (disable swap via sysctl)
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: Ensure swap is disabled on boot
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+)'
    replace: '#\1'

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Kubernetes apt keyring 
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    filename: kubernetes
    state: present
    mode: '0644'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install kubeadm, kubectl, and kubelet
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubectl
      - kubelet
    state: present
    update_cache: no
