- name: Ensure required kernel modules are listed in /etc/modules-load.d/k8s.conf
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: true
  loop:
    - overlay
    - br_netfilter

- name: Load required kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Set sysctl params for Kubernetes networking
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/10-k8s.conf
    line: "{{ item }}"
    create: true
  loop:
    - "net.bridge.bridge-nf-call-ip6tables = 1"
    - "net.bridge.bridge-nf-call-iptables = 1"
    - "net.ipv4.ip_forward = 1"

- name: Apply sysctl params
  ansible.builtin.command: sysctl -f /etc/sysctl.d/10-k8s.conf

- name: Disable swap
  ansible.builtin.command: swapoff -a

- name: Ensure swap is disabled on boot
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+)'
    replace: '#\1'
