- name: Get current time on control host
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get current date
      ansible.builtin.command: date "+%Y-%m-%d %H:%M:%S"
      register: current_time

    - name: Set fact for current time
      ansible.builtin.set_fact:
        synced_time: "{{ current_time.stdout }}"

- name: Set time on all nodes
  hosts: all
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: Set system time to match control host
      ansible.builtin.command: date -s "{{ hostvars['localhost']['synced_time'] }}"
      
- name: Deploy Kubernetes cluster
  hosts: all
  become: true
  vars_files:
    - vault.yml
  roles:
    - k8s_cluster