- name: Test connectivity with ping
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

- name: Run network tasks
  hosts: node1
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Включить сетевые задачи
      ansible.builtin.import_tasks: network_tasks.yml
      tags: notest

- name: Add Debian 12 (bookworm) repositories
  hosts: node1
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Add repositories
      ansible.builtin.import_tasks: add_repositories.yml
      tags: notest 

- name: Install dependencies
  hosts: node1
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Install dependencies
      ansible.builtin.import_tasks: install_dependencies.yml
      tags: notest

- name: Configure Kubernetes prerequisites
  hosts: node1
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Apply Kubernetes prerequisites
      ansible.builtin.import_tasks: k8s_prereqs.yml
      tags: notest

- name: Движки для Kuber
# cri-o -> 0
# containerd -> 1
# Docker + cri-dockerd -> 2
  hosts: node1
  gather_facts: false  
  become: true
  become_method: sudo
  vars_files:
    - branch_var.yml
  tasks:
    - name: cri-o
      ansible.builtin.import_tasks: cri-o.yml
      when: branch_mode == 0

    - name: containerd
      ansible.builtin.import_tasks: containerd.yml
      when: branch_mode == 1

    - name: cri-dockerd
      ansible.builtin.import_tasks: cri-dockerd.yml
      when: branch_mode == 2
