- name: Test connectivity with ping
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

- name: Run network tasks
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Включить сетевые задачи
      ansible.builtin.import_tasks: network_tasks.yml
      tags: notest

- name: Add Debian 12 (bookworm) repositories
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Add repositories
      ansible.builtin.import_tasks: add_repositories.yml
      tags: notest

- name: Install dependencies
  hosts: all:main_control_panel:control_panel
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Install dependencies
      ansible.builtin.import_tasks: install_dependencies.yml
      tags: notest

- name: Configure Kubernetes prerequisites
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Apply Kubernetes prerequisites
      ansible.builtin.import_tasks: k8s_prereqs.yml
      