- name: Test connectivity with ping
  hosts: node2
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:
    - name: Включить сетевые задачи
      ansible.builtin.import_tasks: network_tasks.yml
