- name: Test connectivity with ping
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

- name: Run network tasks
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Включить сетевые задачи
      ansible.builtin.import_tasks: network_tasks.yml
      tags: untest

- name: Add Debian 12 (bookworm) repositories
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Add repositories
      ansible.builtin.import_tasks: add_repositories.yml
      tags: untest 

- name: Install dependencies
  hosts: all:control_panel
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Install dependencies
      ansible.builtin.import_tasks: install_dependencies.yml
      tags: untest

- name: Configure Kubernetes prerequisites
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Apply Kubernetes prerequisites
      ansible.builtin.import_tasks: k8s_prereqs.yml
      tags: untest

- name: Установка движков для Kuber
# cri-o -> 0
# containerd -> 1
# Docker + cri-dockerd -> 2
  hosts: all
  gather_facts: false  
  become: true
  become_method: sudo
  vars_files:
    - branch_var.yml
  tasks:
    - name: cri-o
      ansible.builtin.import_tasks: cri-o.yml
      when: branch_mode == 0
      tags: untest

    - name: containerd
      ansible.builtin.import_tasks: containerd.yml
      when: branch_mode == 1
      tags: untest

    - name: cri-dockerd
      ansible.builtin.import_tasks: cri-dockerd.yml
      when: branch_mode == 2      
      tags: untest

- name: Развёртывание Kubernetes
# cri-o -> 0
# containerd -> 1
# Docker + cri-dockerd -> 2
  hosts: control_panel:workers
  gather_facts: false  
  become: true
  become_method: sudo
  vars_files:
    - branch_var.yml
  tasks:
    - name: all in one
      ansible.builtin.import_tasks: all_in_one.yml
      when: branch_mode == 0 or branch_mode == 1   
      tags: test

    - name: ha cluster
      ansible.builtin.import_tasks: cluster.yml
      when: branch_mode == 2   
      tags: test
