- name: Remove cdrom repository from sources.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb cdrom:'
    state: absent

- name: Add main contrib non-free non-free-firmware repo
  ansible.builtin.apt_repository:
    repo: "{{ debian_main_repo }}"
    state: present
    filename: 'debian-main'

- name: Add updates repo
  ansible.builtin.apt_repository:
    repo: "{{ debian_updates_repo }}"
    state: present
    filename: 'debian-updates'

- name: Add security repo
  ansible.builtin.apt_repository:
    repo: "{{ debian_security_repo }}"
    state: present
    filename: 'debian-security'
