- name: Ensure required kernel modules are listed in /etc/modules-load.d/k8s.conf
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: true
  loop: "{{ kernel_modules }}"

- name: Load required kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kernel_modules }}"

- name: Apply sysctl params
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop: "{{ sysctl_params }}"

- name: Set swappiness to 0 (disable swap via sysctl)
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: Ensure swap is disabled on boot
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+)'
    replace: '#\1'

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Kubernetes apt keyring 
  ansible.builtin.apt_key:
    url: "{{ k8s_apt_key }}"
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "{{ k8s_apt_repo }}"
    filename: kubernetes
    state: present
    mode: '0644'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install kubeadm, kubectl, and kubelet
  ansible.builtin.apt:
    name: "{{ kube_packages }}"
    state: present
    update_cache: no
